

service: curso-sls-api-key

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1

  apiKeys:
    - $file(./config.${self:provider.stage}.json):API_KEY}


functions:
  hello:
    handler: handler.hello
    events:
      - http:
         path: /
         method: get
         private: true

